[tool.poetry]
name = "ibm"
version = "0.1.0"
description = ""
authors = ["Jonathan do Ouro <jonathan.ouro@neuralmind.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
